site_name: 'CI/CD Workflows'
site_url: https://automated-workflows.readthedocs.io/
site_description: CI/CD Wokflows Project Documentation.
site_author: Konstantinos Lampridis

repo_url: https://github.com/boromir674/automated-workflows/
repo_name: boromir674/automated-workflows
edit_uri: blob/main/docs/

theme:
  # 1
  name: material
  icon:
    logo: material/palette
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    default: material/tag

  # favicon: images/favicon.png
  features:
    - navigation.path
    - navigation.top
    - navigation.footer
    # - navigation.indexes
  # navigation.instant break mermaid
  # features:
  #   - navigation.tracking

    # - navigation.instant

plugins:
  # Enable jinja inside your markdown files
  # https://github.com/fralau/mkdocs_macros_plugin
  # - macros

  # Authors need installation
  # - git-authors

  - tags:
      tags_file: tags.md

  # BASIC SEARCH PLUGIN
  - search

  # MERMAID Render Support
  - mermaid2

  # - literate-nav:
  #     nav_file: SUMMARY.md

  - section-index

markdown_extensions:
  - pymdownx.highlight
  
nav:
  # each item in the list, renders a left side navigation item/page
  - Home:
    - "Quick Start": index.md
  - Guides:
    - "CD: Dockerhub": "guides/guide_setup_cicd.md"
    - "CD: PyPI": "guides/guide_setup_pypi.md"
    - "CI: Build(s) Testing": "guides/guide_test_build.md"
  - References:
    # Build, CD
    - "Docker": "api/ref_docker.md"
    - "Github Release": "api/ref_gh_release.md"
    - "PyPI": "api/ref_pypi_env.md"
    - "Test Build": "api/ref_test_build.md"
    - "Docs": "api/ref_docs.md"
    - "Lint": "api/ref_lint.md"
    - "Code Visualization": "api/ref_pydeps.md"
    - "Git Ops": "api/ref_gitops_pr_to_boarding.md"
    - "Single Status": "api/ref_single_status.md"
  - Topics:
    - "Test Suite": topics/tests_index.md
    - "Workflow 'go-single-status.yml'": "topics/workflow_single_status_idea.md"

  - tags: tags.md


extra:
  generator: false
