site_name: 'CI/CD Workflows'
site_url: https://automated-workflows.readthedocs.io/
site_description: CI/CD Wokflows Project Documentation.
site_author: Konstantinos Lampridis
repo_url: https://github.com/boromir674/automated-workflows/
repo_name: boromir674/automated-workflows
edit_uri: blob/main/docs/
theme:
  # 1
  name: material
  icon:
    logo: material/palette
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    default: material/tag
  # favicon: images/favicon.png
  features:
    - navigation.path
    - navigation.top
    - navigation.footer
    # - navigation.indexes
  # navigation.instant break mermaid
  # features:
  #   - navigation.tracking
# - navigation.instant

  ### CSS DESIGN ###
  # Allow writting css to a single css file,
  # eg avoids need to add <style> elements in markdown, in case custom styles required

  # extra_css:
  #   - css/extra.css


plugins:
  # Enable jinja inside your markdown files
  # - allows {% include %} statements
  # - requires careful escape of double-braces in markdown
  # - requires wrapping content between {% raw %} and {% endraw %}
  # https://github.com/fralau/mkdocs_macros_plugin
  - macros:
      include_dir: docs/includes
  # Authors need installation
  # - git-authors
  - tags:
      tags_file: tags.md
  # BASIC SEARCH PLUGIN
  - search
  # MERMAID Render Support
  - mermaid2
  # - literate-nav:
  #     nav_file: SUMMARY.md
  - section-index

markdown_extensions:
  - pymdownx.highlight
  ### ADMONITIONS ###
  # enabled block kelements such as example, note, info, warning, tip, etc
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition

  ### SUPERFENCES ###
  # arbitrary nesting of code and content blocks inside each other,
  # including admonitions, tabs, lists and all other elements
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#superfences
  # this custom fence defined below with name 'mermaid' is required
  # to prevent superfences from breaking mermaid default syntax (3 backticks)!
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  ### TABBED ###
  # usage of content tabs, a simple way to group related content and
  # code blocks under accessible tabs.
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#tabbed
  - pymdownx.tabbed:
      alternate_style: true

  ### GRIDS ###
  - attr_list
  - md_in_html

  ### ICONS/EMOJIS ###
  # https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#with-colors-docsstylesheetsextracss
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  ### On-HOVER TOOLTIP ###
  # abbr by default supports tooltips on url links
  - abbr
  # if attr_list is also added, then tooltips on other html elements are supported as below:
  # ie :material-information-outline:{ title="Important information" }



#### SIDE NAVIGATION - DESIGN ####
nav:
  # each item in the list, renders a left side navigation item/page
  - Home:
      - "Quick Start": index.md
  - How-to Guides:
      - "CD: Dockerhub": "guides/guide_setup_cicd.md"
      - "CD: PyPI": "guides/guide_setup_pypi.md"
      - "CI: Build(s) Testing": "guides/guide_test_build.md"
      - "Git Ops":
          - guides/gitops/index.md
          - "Setup":
            - "Setup Release Me - Phase 1": "guides/gitops/setup/guide_setup_gitops_release_me.md"
            - "Setup Release Me - Phase 2": "guides/gitops/setup/guide_setup_gitops_release_me_phase_2.md"
            - "Automated Acceptance": "guides/gitops/setup/guide_setup_main_automated_acceptance.md"
            - "Manual Acceptance": "guides/gitops/setup/guide_setup_main_manual_acceptance.md"
            - "Automatic Tag on Main": "guides/gitops/setup/guide_setup_auto_tag_main.md"
            - "Automatic Clean-Up": "guides/gitops/setup/guide_setup_automatic_tags_deletion.md"
          - "RUN":
            - "Release Me": "guides/gitops/run/guide_run_gitops_release_me_process.md"
  - API References:
      - "Docker": "api/ref_docker.md"
      - "Github Release": "api/ref_gh-release.md"
      - "PyPI": "api/ref_pypi_env.md"
      - "Test Build": "api/ref_test_build.md"
      - "Docs": "api/ref_policy_docs.md"
      - "Lint": "api/ref_lint.md"
      - "Code Visualization": "api/ref_python_imports.md"
      - "Git Ops - Boarding": "api/ref_gitops_pr_to_boarding.md"
      - "Single Status": "api/ref_single_status.md"
      - "PR to Boarding": api/ref_go-pr-to-boarding.md
      - "Single Job Status": api/ref_go-single-status.md
      - pypi.yml: api/ref_pypi.md
      - "Git Ops - PR to Release": api/ref_go-pr-to-release.md
      - "Git Ops - PR to Main": api/ref_go-pr-to-main.md
      - "Git Ops - Auto Merge to Main": "api/ref_go-auto-merge-main.md"
      - "Git Ops - Tag Main": api/ref_go-tag-main.md
      - "Git Ops - Clean-up Tags": api/ref_go-delete-tags.md
  - Topics:
      - "Single Status Workflow'": "topics/workflow_single_status_idea.md"
      - "Git Ops":
          - "topics/gitops/index.md"
          - "Process - Release Me": "topics/gitops/release-me-process.md"
          - "Process - Auto Prod": "topics/gitops/release-me-process_phase_2.md"
      - "Test Suite": topics/tests_index.md
      - "Semantic Release": topics/semantic-release.md
  - "Development": topics/dev/dev-notes.md
  - tags: tags.md
extra:
  generator: false
