site_name: 'CI/CD Workflows'
site_url: https://automated-workflows.readthedocs.io/
site_description: CI/CD Wokflows Project Documentation.
site_author: Konstantinos Lampridis
repo_url: https://github.com/boromir674/automated-workflows/
repo_name: boromir674/automated-workflows
edit_uri: blob/main/docs/
theme:
  # 1
  name: material
  icon:
    logo: material/palette
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    default: material/tag
  # favicon: images/favicon.png
  features:
    - navigation.path
    - navigation.top
    - navigation.footer
    # - navigation.indexes
  # navigation.instant break mermaid
  # features:
  #   - navigation.tracking
# - navigation.instant

plugins:
  # Enable jinja inside your markdown files
  # https://github.com/fralau/mkdocs_macros_plugin
  # - macros

  # Authors need installation
  # - git-authors
  - tags:
      tags_file: tags.md
  # BASIC SEARCH PLUGIN
  - search
  # MERMAID Render Support
  - mermaid2
  # - literate-nav:
  #     nav_file: SUMMARY.md
  - section-index
markdown_extensions:
  - pymdownx.highlight
nav:
  # each item in the list, renders a left side navigation item/page
  - Home:
      - "Quick Start": index.md
  - How-to Guides:
      - "CD: Dockerhub": "guides/guide_setup_cicd.md"
      - "CD: PyPI": "guides/guide_setup_pypi.md"
      - "CI: Build(s) Testing": "guides/guide_test_build.md"
      - "Git Ops":
          - guides/gitops/index.md
          - "Setup Release Me - Phase 1": "guides/gitops/guide_setup_gitops_release_me.md"
          - "Setup Release Me - Phase 2": "guides/gitops/guide_setup_gitops_release_me_phase_2.md"
  - API References:
      - "Docker": "api/ref_docker.md"
      - "Github Release": "api/ref_gh-release.md"
      - "PyPI": "api/ref_pypi_env.md"
      - "Test Build": "api/ref_test_build.md"
      - "Docs": "api/ref_policy_docs.md"
      - "Lint": "api/ref_lint.md"
      - "Code Visualization": "api/ref_python_imports.md"
      - "Git Ops - Boarding": "api/ref_gitops_pr_to_boarding.md"
      - "Single Status": "api/ref_single_status.md"
      - "PR to Boarding": api/ref_go-pr-to-boarding.md
      - "Single Job Status": api/ref_go-single-status.md
      - pypi.yml: api/ref_pypi.md
      - "Git Ops - PR to Release": api/ref_go-pr-to-release.md
      - "Git Ops - PR to Main": api/ref_go-pr-to-main.md
      - "Git Ops - Auto Merge to Main": api/ref_go-auto-merge-main.md
  - Topics:
      - "Single Status Workflow'": "topics/workflow_single_status_idea.md"
      - "Git Ops":
          - "topics/gitops/index.md"
          - "Process - Release Me": "topics/gitops/release-me-process.md"
          - "Process - Auto Prod": "topics/gitops/release-me-process_phase_2.md"
      - "Test Suite": topics/tests_index.md
      - "Semantic Release": topics/semantic-release.md
  - "Development": topics/dev/dev-notes.md
  - tags: tags.md
extra:
  generator: false
