#####################################
## Auto Merge PR to Main  - GitOps ##
#####################################

# Part of 'release-me' Git Ops Process: User Br -> release -> main

# Triggers on pushed auto-prod-* tags

# EG
# export tt='auto-prod-1.3.0'
# OR
# export tt='auto-prod-1.2.1-dev'
# git tag -d "$tt"; git push --delete origin "$tt"; git tag "$tt" && git push origin "$tt"

#### Does the following:
#  1. Derives a Git Tag to make an RC Tag
#  2. Tags commit on release branch with RC Tag
####

on:
  push:
    tags:
      - auto-prod-*

jobs:
  # The cicd-test Suite references the test branch
  # So, we push it to have the same state as, before the RC Tag Push
  # which tag triggers CI Tests
  put_test_branch_to_release:
    uses: ./.github/workflows/_update_test_branch.yml
    with:
      target_branch: ${{ vars.GIT_RELEASE_BRANCH || 'release' }}
    secrets:
      GH_TOKEN_CONTENTS_RW: ${{ secrets.GA_WORKFLOWS_CI_PR_RW_AND_ACTIONS_RW }}

  # GIT OPS Workflow
  auto_merge_pr_to_main:
    needs: put_test_branch_to_release
    if: always()
    uses: ./.github/workflows/go-auto-merge-main.yml
    with:
      main_branch: ${{ vars.GIT_MAIN_BRANCH || 'main' }}
      release_branch: ${{ vars.GIT_RELEASE_BRANCH || 'release' }}
      commit_message: 'Automated Workflows'
    secrets:
      pat_token: ${{ secrets.GA_WORKFLOWS_CI_PR_RW_AND_ACTIONS_RW }}
