#####################################
## Auto Merge PR to Main  - GitOps ##
#####################################

# Part of 'release-me' Git Ops Process: User Br -> release -> main

# Triggers on pushed auto-prod-* tags

# EG
# export tt='auto-prod-1.3.0'
# OR
# export tt='auto-prod-1.2.1-dev'
# git tag -d "$tt"; git push --delete origin "$tt"; git tag "$tt" && git push origin "$tt"

#### Does the following:
#  1. Derives a Git Tag to make an RC Tag
#  2. Tags commit on release branch with RC Tag
####

on:
  push:
    tags:
      - auto-prod-*

jobs:
  auto_merge_pr_to_main:
    uses: ./.github/workflows/go-auto-merge-main.yml
    with:
      main_branch: ${{ vars.GIT_MAIN_BRANCH || 'main' }}
      release_branch: ${{ vars.GIT_RELEASE_BRANCH || 'release' }}
      commit_message: 'Automated Workflows'
    secrets:
      pat_token: ${{ secrets.GA_WORKFLOWS_CI_PR_RW_AND_ACTIONS_RW }}
