##########################
## Delete Tags - GitOps ##
##########################

# JOB: Delete Git Tags, acting as push events that trigger Git Ops Workflows
# TRIGGER: when PR from 'release' to 'main/master' Closes with Code Merge
#   AND PR title starts with '[GITOPS]'
#   AND PR has 'auto-deploy' Label
# REQUIRES: Secret GH_PAT_CONTENT_RW with Repo Content RW permission/access

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - master
jobs:
  delete_tags:
    if: github.event.pull_request.merged == true &&
      github.event.pull_request.head.ref == 'release' &&
      contains(github.event.pull_request.labels.*.name, 'auto-deploy')
    uses: ./.github/workflows/go-delete-tags.yml
    secrets:
      # pass in GITHUB PAT with Repo Content RW permission/access
      GH_PAT_CONTENT_RW: ${{ secrets.GA_WORKFLOWS_CI_PR_RW_AND_ACTIONS_RW }}
