name: "Pull Request Labeler"

on:
  - pull_request_target

jobs:
  label_PR:
    runs-on: ubuntu-latest
    # This Job behaves as a Listener to PR events, and each step is a Handler
    steps:
      # HANDLER 1: Label PR, given file changes and Labeling Rules in '.github/labeler.yml'
      - uses: actions/labeler@v5
        with:
          # PAT with permission for label creation events to trigger other Workflows
          repo-token: ${{ secrets.GA_WORKFLOWS_CI_TRIGGER_WORKFLOW }}
