name: 'Automated Workflows - CI Pipeline'

on:
  push:
    branches:
      - main
    tags:
      - v*
      - run-ci
  pull_request:
    branches:
      - main
env:
  # Groups Test Cases into sets of 4 and dedicate a Job, to run each set
  # Job runs on a machine with 4 cpu threads; see pytest-xdist
  JOB_MATRIX: "{\"tests_filter\": [\"docker_pol0 or docker_pol1\", \"docker_pol2 or docker_pol3\", \"code_viz or docker_test_when_tag_not_given\", \"pypi_test or static_code\"]}"

jobs:
  test_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Automated Test Suite
        uses: actions/checkout@v4
        with:
          repository: 'boromir674/cicd-test'
          ref: 'main'
          path: 'cicd-test'
      - name: Setup Python ${{ env.py_ver }}
        env:
          py_ver: '3.10'
        uses: actions/setup-python@v4
        with:
          python-version: '${{ env.py_ver }}'
      - name: Install tox
        run: pip install 'tox<4.0'

      - name: Pin Python Dependencies
        run: |
          cd cicd-test
          tox -e pin-deps

      - name: Run Automated Test Suite
        env:
          GH_TOKEN: ${{ github.token }}
          CICD_TEST_GH_TOKEN: ${{ secrets.CICD_TEST_GH_TOKEN }}
        run: |
          cd cicd-test
          tox -e test -vv
