name: 'CI/CD Pipeline'

on:
  push:
    branches:
      - main
      # exclude pushes to 'release' branch
      - '!release'
    tags:
      - v*
      - run-ci

jobs:
  test_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Automated Test Suite
        uses: actions/checkout@v4
        with:
          repository: 'boromir674/cicd-test'
          ref: 'main'
          path: 'cicd-test'
      - name: Setup Python ${{ env.py_ver }}
        env:
          py_ver: '3.10'
        uses: actions/setup-python@v4
        with:
          python-version: '${{ env.py_ver }}'
      - name: Install tox
        run: pip install 'tox<4.0'

      - name: Pin Python Dependencies
        working-directory: cicd-test
        run: tox -e pin-deps

      - name: Run Automated Test Suite
        env:
          CICD_TEST_GH_TOKEN: ${{ secrets.CICD_TEST_GH_TOKEN }}
        working-directory: cicd-test
        run: tox -e test -vv
