#########################################################
##     Reusable Documentation Site Builder Workflow    ##
#########################################################

## Mkdocs or Sphinx Documentation (Static) Site Building ##

# - For mkdocs requires a 'mkdocs.yml' config file in the repo root
# - For sphinx requires a 'docs/conf.py' config file in the 'docs/' directory
# - For both Build Tools, expects the docs source files to be in the 'docs/' directory

# 1. Creates Docs reproducible Build environemnt, with exact python dependencies
# 2. Runs one or more Docs Build commands and verifies they succeed
# 3. Optionally uploads built docs site to CI Artifacts for later retrieval

# Assumptions:
# - project supports editable (-e) install, to make the source code available in PYTHONPATH
# - pyproject.toml integrates/supports uv


name: Docs Build

on:
  workflow_call:
    inputs:
      # Docs Builder - Settings #
      build_tool:
        required: false
        default: 'mkdocs'
        description: "Documentation build tool to use. Options: 'mkdocs' or 'sphinx'. Default is 'mkdocs'"
        type: string

      # Upload build to CI Artifacts
      upload_distro:
        required: false
        default: false
        type: boolean
        description: "Whether to upload built docs distro to CI Artifacts"

      # Trigger Behavior - Settings #
      default_trigger:
        required: false
        default: true
        description: "Default trigger for the workflow. If true the 'default behavior' is to run on call. If false, the 'default behavior' is to be skipped."
        type: boolean

      override:
        required: false
        description: "Override the default trigger, 'true' gurantees run, 'false' not run"
        type: string  # IMPORTANT: must be string, to model 3 states {true, false, none}

      # Python Environment - Settings #
      python_version:
        required: false
        default: '3.11'
        description: "Python version to use for the job. Default is 3.11"
        type: string

jobs:
  test:
    if: inputs.override == 'true' || (inputs.override != 'false' && inputs.default_trigger == true)
    runs-on: 'ubuntu-latest'
    env:
      BUILD_OUTPUT_DIR: docs-dist  # for internal plumbing / DRYness
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${ inputs.python_version }
        uses: actions/setup-python@v5
        with:
          python-version: '${{ inputs.python_version }}'

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: 'Export pinned Prod + Docs dependencies'
        run: uv export --no-emit-project --no-dev --extra docs --frozen --format requirements-txt -o requirements.txt

      # 1a. Install dependencies in virtualenv
      - name: 'Install "Prod + Docs" dependencies'
        run: |
          uv venv
          uv pip install --no-deps -r requirements.txt

      # here the .venv is built with the exact dependencies

      ## 1b. Install Package in 'edit' mode ##
      - name: 'Install Package in Edit mode'
        run: uv pip install --no-deps -e .

      ## Create Docs Build/Test script, based on input Docs Builder Tool
      - name: "Create Docs Build/Test script for Docs Builder Tool '${{ inputs.build_tool }}'"
        id: create_docs_build_script
        run: |
          echo "#!/bin/bash" > docs_build.sh

          if [ "${{ inputs.build_tool }}" = "mkdocs" ]; then
            echo "mkdocs build --site-dir dist/docs" >> docs_build.sh
          elif [ "${{ inputs.build_tool }}" = "sphinx" ]; then
            echo "sphinx-build -E -b doctest docs dist/docs" >> docs_build.sh
            echo "sphinx-build -E -b html docs dist/docs" >> docs_build.sh
            echo "sphinx-build -b spelling docs dist/docs" >> docs_build.sh
            echo "sphinx-build -b linkcheck docs dist/docs || 'true'" >> docs_build.sh
          else
            echo "[ERROR] Unsupported docs build tool: ${{ inputs.build_tool }}. Supported: mkdocs, sphinx"
            exit 1
          fi
          chmod +x docs_build.sh
          echo SCRIPT START
          cat docs_build.sh
          echo SCRIPT END

          echo "DOCS_TEST_SCRIPT=docs_build.sh" >> $GITHUB_OUTPUT

      - name: 'Display Docs Build/Test Script in Summary'
        run: |
          echo "# Docs Test script" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`sh" >> $GITHUB_STEP_SUMMARY
          cat "${{ steps.create_docs_build_script.outputs.DOCS_TEST_SCRIPT }}" >> $GITHUB_STEP_SUMMARY

          # do not use cat "${{ steps.create_docs_build_script.outputs.DOCS_TEST_SCRIPT }}" >> $GITHUB_STEP_SUMMARY
          # read file contents and pipe through echo to dump to summary
          # while IFS= read -r line; do
          #   echo "$line" >> $GITHUB_STEP_SUMMARY
          # done < docs_build.sh

          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

      #### 2. Build Documentation HTML/CSS/JS from docs sources ####
      - name: 'Run Docs Build Process and perform Tests during build'
        run: |
          . .venv/bin/activate

          echo "[INFO] Running Docs Build/Test script: ${{ steps.create_docs_build_script.outputs.DOCS_TEST_SCRIPT }}"
          ./${{ steps.create_docs_build_script.outputs.DOCS_TEST_SCRIPT }}

      - name: "Upload Docs HTML/CSS/JS bundle to CI Artifacts"
        if: inputs.upload_distro
        uses: actions/upload-artifact@v4
        with:
          overwrite: false
          name: docs
          path: dist/docs
          if-no-files-found: error
