###############################
## Open Pull Request to Main ##
##     Reusable Workflow     ##
###############################

name: Open PR to Main

# WHEN a PR 'release-train' --> 'release' is closed with code merge
# THEN Open PR: 'release' --> 'Main'

# - designed to be triggered as part of 'release-me' tag event

# Participates in `release-me` GitOps Process:
#  User Br --PR -> Release --PR -> main 

on:
  workflow_call:
    inputs:
      # Head Branch
      release_branch:
        description: 'Release Branch; dedicated for Sem Ver bump, Changelog updates, making RC Releases (Release Candidate), deploying to Staging, etc'
        required: true
        default: 'release'
        type: string
      main_branch:
        default: 'main'
        description: 'Name of the Main Branch. Example: main, master'
        required: false
        type: string
    secrets:
      PR_RW_AND_ACTIONS_RW:
        description: 'GitHub Token, with read/write permissions to PRs and read/write permissions to Github Actions Workflows'
        required: true

jobs:
  pr_to_main:
    runs-on: ubuntu-latest
    env:
      RELEASE: ${{ inputs.release_branch }}
      MAIN_BR: ${{ inputs.main_branch }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 0 indicates all history for all branches and tags.
          set-safe-directory: ''  # `git config --global --add safe.directory <path>`
          token: '${{ secrets.PR_RW_AND_ACTIONS_RW }}'

      ##### Open PR: Release  -->  Main/Master #####
      - name: "Open PR  'head': ${{ env.RELEASE }} --> 'base': ${{ env.MAIN_BR }}"
        env:
          GH_TOKEN: ${{ secrets.PR_RW_AND_ACTIONS_RW }}
        run: |
          gh pr create --head "${{ env.RELEASE }}" --base "${{ env.MAIN_BR }}" \
            --title "[GITOPS] - Merging '${{ env.RELEASE }}' in '${{ env.MAIN_BR }}' - Releasing into Production" \
            --body "## :rocket: Releasing into Production :rocket:
            
            This PR marks a pivotal moment in our deployment cycle, signaling that all changes on the **Release** branch are deemed ready for production.  
            It represents the collective decision of our developers that the changes bundled in the Release are suitable to be released together.

            ### What's Happening in This PR?

            - We are merging the '${{ env.RELEASE }}' branch into the '${{ env.MAIN_BR }}' branch.
            - This is the last Pull Request, transitioning us from the release phase to the production phase.

            ### :white_check_mark: Automatic Merging Upon CI Checks :white_check_mark:
            
            Before merging into '${{ env.MAIN_BR }}', this PR **should be checked**, for meetings some standards, such as:

            - All CI Jobs are Green / Passing
            - Acceptance Criteria/Tests passed, on a Staging Deployment
            - Code Review is approved by at least one developer

            "
        # ### :warning: Manual Merging Upon CI Checks and Code Review :warning:

        # If the above conditions are not met, this PR will be manually merged into the '${{ env.MAIN_BR }}' branch, by a developer.
